apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: appmesh-demo
  region: us-west-2
vpc:
  id: "vpc-01916cdb9af0b13c5"
  subnets:
    private:
      us-west-2a:
        id: "subnet-02df6460ee653107b"  
      us-west-2b:
        id: "subnet-09841b694c3192b5e"  
      us-west-2c:
        id: "subnet-043609911265d0577"                  
nodeGroups:
  - name: default
    instanceType: m5.large
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        appMesh: true
        xRay: true
