apiVersion: v1
appVersion: "1.0"
description: This is an example helm char to deploy colorapp microservice (https://github.com/aws/aws-app-mesh-examples)
name: colorapp-appmesh-demo
version: 0.1.1
home: https://github.com/aws/aws-app-mesh-examples
